### ISSUE TITLE
Sample solutions needed for all languages.

### ISSUE THREAD

**Issue by alectunbridge** [MCR-Digital/apprentice-boot-camp-fundamentals-1#22]
Sample solutions are only available for Java - should include other languages as well.
Since the exercises build on one another the sample solutions are important, lest those who are struggling get stuck.

**Comment by mrmanc** [comment]
To do:
- [ ] Find someone to help with C#
- [ ] Create JS solutions

**Comment by mrmanc** [comment]
This is a duplicate of #83
