### ISSUE TITLE
Check/update the Java import instructions

### ISSUE THREAD

**Issue by mrmanc** [MCR-Digital/apprentice-boot-camp-fundamentals-1#55]

**Comment by mrmanc** [comment]
That’s great. It was just a quick check that we do before each boot camp. I’ve got a feeling that IntelliJ changed their import UI since the last boot camp and there is a slide that provides instructions, so just need to check whether it needs updating.

**Comment by harvy2004** [comment]
Ok will check slides and update if needed.
Maybe worth adding README to all languages on how to setup? More inline with how READMEs work in the real world.

**Comment by mrmanc** [comment]
That’s a good shout. Go for it! 😃
