### ISSUE TITLE
People struggled to form wild inheritance trees

### ISSUE THREAD

**Issue by mrmanc** [MCR-Digital/apprentice-boot-camp-fundamentals-1#75]
There wasn’t a great deal of examples of really deep inheritance trees. This exercise might not quite have landed with them. Might be worth simply showing them complex examples of how people might choose to model the deck, and getting them to discuss the pros and cons.

**Comment by helloheatherw** [comment]
Perhaps we could use an example to demonstrate when we mean by a wild inheritance tree? We've used some car examples throughout so maybe something related to this.

**Comment by mrmanc** [comment]
Yeah, we could certainly show a diagram that has something like Card <- Playing Card <- (Heart Card, Club Card, Spade Card, Diamond Card) <- (Ace of Hearts, One of Hearts etc).

**Comment by mrmanc** [comment]
Keeping it simple by leaving this out.
