### ISSUE TITLE
Jest caused issues

### ISSUE THREAD

**Issue by mrmanc** [MCR-Digital/apprentice-boot-camp-fundamentals-1#79]
We didn’t mention they should have it set up, and at least one apprentice wasn’t familiar with it. We should provide them with more guidance around setting up and how to run the tests.

This was shared for the JS apprentices:

```shell
npm i && npx jest --watch
```
Then use `p` and enter `cards.test` for the test filter.

**Comment by helloheatherw** [comment]
I was surprised that using Jest caused any issues, but perhaps we could have a slide / section on the read me that mentions how to get the project up and running? I can also add the jest watch script to the package.json.

Specifying the individual test was useful when it was shared, but I think it's fine to run all the tests in watch mode as the project has a full set of passing tests when it's first run.

I'm happy to pick this one up!

**Comment by harvy2004** [comment]
I agree as well. I already had node installed on my machine and I just cloned the project ran `npm install && test` and it worked fine. I have no idea if I had installed jest seperately to that. I assume `installl` pulled it down for me?

**Comment by mrmanc** [comment]
> we could have a slide / section on the read me that mentions how to get the project up and running

I like this idea. @harvy2004 created something similar for the `dotnet` folder so this would be great. Getting these things working can be as simple as running a single command, but if you don’t know it then it’s not easy 😃 

> it's fine to run all the tests in watch mode

That is a great shout. We encourage them to always run all of the tests, particularly since the tests aren’t slow so that will help with this.

> I'm happy to pick this one up!

🎉  Thanks for picking this up @helloheatherw!
