### ISSUE TITLE
One of the shuffles doesn’t shuffle

### ISSUE THREAD

**Issue by mrmanc** [MCR-Digital/apprentice-boot-camp-fundamentals-1#97]
Shuffles a transient list created on the fly from an array.

**Comment by alectunbridge** [comment]
Hmm can't seem to find the offending code - can only assume that you're referencing this line of code:

**Comment by mrmanc** [comment]
That is indeed the line of code. Fascinating! I never realised that the returned list acted as a bridge! So it’s shuffling the array, by providing `Collections.shuffle()` with a list. Closing as it’s not an issue 😃
